version: '2.1'

services:
  hub:
    image: elgalu/selenium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - GRID=true
      - CHROME=false
      - FIREFOX=false      
  chrome:
    image: elgalu/selenium
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - MAX_INSTANCES=5
      - MAX_SESSIONS=5
  firefox:
    image: elgalu/selenium
    depends_on:
      - hub
    volumes:
      - /dev/shm:/dev/shm
    privileged: true
    environment:
      - PICK_ALL_RANDOM_PORTS=true
      - SELENIUM_HUB_HOST=hub
      - SELENIUM_HUB_PORT=4444
      - SELENIUM_NODE_HOST={{CONTAINER_IP}}
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - GRID=false
      - CHROME=false
      - FIREFOX=true
      - MAX_INSTANCES=5
      - MAX_SESSIONS=5 
